/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryPolicyRouteImport } from './routes/delivery-policy'
import { Route as EventsRouteImport } from './routes/events'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryPolicyRoute = DeliveryPolicyRouteImport.update({
  id: '/delivery-policy',
  path: '/delivery-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/delivery-policy': typeof DeliveryPolicyRoute
  '/events': typeof EventsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/delivery-policy': typeof DeliveryPolicyRoute
  '/events': typeof EventsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/delivery-policy': typeof DeliveryPolicyRoute
  '/events': typeof EventsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/delivery-policy'
    | '/events'
    | '/refund-policy'
    | '/terms-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/delivery-policy'
    | '/events'
    | '/refund-policy'
    | '/terms-conditions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/delivery-policy'
    | '/events'
    | '/refund-policy'
    | '/terms-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DeliveryPolicyRoute: typeof DeliveryPolicyRoute
  EventsRoute: typeof EventsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-policy': {
      id: '/delivery-policy'
      path: '/delivery-policy'
      fullPath: '/delivery-policy'
      preLoaderRoute: typeof DeliveryPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DeliveryPolicyRoute: DeliveryPolicyRoute,
  EventsRoute: EventsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsConditionsRoute: TermsConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
